#!/usr/bin/env bash

# 这个脚本检查W连接状态，返回0表示已连接，返回1表示未连接。

export LANG="en"

ip link show | grep -q '^[0-9].*ppp'

if  [[ $? -eq 0 ]]; then
    echo "pppoe-status-exit:0"
    exit 0
else
    echo "pppoe-status-exit:1"
    exit 1
fi